### ISSUE TITLE
Fails to install based on devDependencies

### ISSUE THREAD

**Issue by newtriks** [oncletom/Imager.jsx#7]
On `npm i --save imager.jsx` I get the following error:
```
Error: Cannot find module 'lodash.debounce' from '/Users/newtriks/src/projects/sayansho/sayansho-co-pilot/node_modules/imager.jsx'
```
The postinstall process is run and the devDependencies are not actually installed. I can confirm that installing all the imager.jsx devDependencies locally and then installing imager.jsx works.

**Comment by oncletom** [comment]
Hm weird: it is a devDependency but the build should be ran only if the install is different from `NODE_ENV=production`.

Any reason not to have the devDependencies to be pulled down?

**Comment by newtriks** [comment]
Sorry, I maybe confusing the actual sequence of events causing the problem. The error is thrown when simply trying to install image.jsx as per the instructions in the readme i.e. `npm i --save imager.jsx`. 

I was stating that if I manually installed the dev dependencies in the imager.jsx package.json e.g. `npm install lodash.debounce etc` then run `npm i --save imager.jsx` it successfully installs.

**Comment by oncletom** [comment]
Okay you are not confused: it seems the `postinstall` script is ran before the devDependencies are completely installed. I published a new version which makes the build manual, if needed. It should be better :-)

**Comment by newtriks** [comment]
Good job @oncletom nice one.

**Comment by oncletom** [comment]
Well thanks for reporting it. Let me know if you have other feedbacks :-)
