### ISSUE TITLE
Cannot find module 'imager.jsx'

### ISSUE THREAD

**Issue by joernroeder** [oncletom/Imager.jsx#9]
Hey,
i've tried to add this module to my project by running `npm install imager.jsx --save` and requiring the module with `var Imager = require('imager.jsx');`

**Comment by oncletom** [comment]
@joernroeder you have made a typo in the package name: 

 ```js
var Imager = require('imager.jsx');
```

Cf. https://github.com/oncletom/Imager.jsx/blob/master/package.json#L2

Have a look a the README for practical examples. Let me know if they are unclear or if you would like more precisions :-)

**Comment by joernroeder** [comment]
Jup, i had a typo in my comment – but not in the code. `Cannot resolve module 'imager.jsx'`
I'm using webpack to serve my files, maybe it has something to do with the missing main file: https://github.com/oncletom/Imager.jsx/blob/master/package.json#L5

**Comment by joernroeder** [comment]
:+1: thanks!

**Comment by thom4parisot** [comment]
Oh well, shipped a patched version. Let me know if you have other feedbacks or if you spot any other issue :-)

I coded that in a day or so for the sake of prototyping workshop so there are certainly areas of improvement!
